### ISSUE TITLE
CORS for live_comments

### ISSUE THREAD

**Issue by Tremax** [xxRockOnxx/obs-fb-live-comments#1]
Hey, i am really appropriate for your work. 
But i can't make it work on my side -- i got CORS issue(in chrome console) when just open index.html(i set valid param) in my browser, it is legit behaviour ?

**Comment by lemuelflores** [comment]
That should not happen. It could probably be because facebook got more strict? or I did something else before.

Anyway,  the CORS issue is happening because we are accessing it thru filesystem instead of a web server that's why the error says Origin is null.

If you know how to setup a webserver, just serve the `index.html` and use the link for that in your Browser Source.

I am also thinking of making a simple page for this because not everyone knows how to do it.

PHP example is the simplest:

```
 php -S localhost:8080 -t .
```

then you can visit `http://localhost:8080` to see it.

I will make a firebase website for this tonight.

**Comment by lemuelflores** [comment]
Firebase website created. Please see README on how to use it.

**Comment by Tremax** [comment]
Will try for sure, thank you for your work!
